// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDxFiDG6gw2ANaSXPAvKUwqfNCrppKa2M',
    appId: '1:730948892593:web:e4080811c7b6cbd7f3ef90',
    messagingSenderId: '730948892593',
    projectId: 'homework5-c7dbe',
    authDomain: 'homework5-c7dbe.firebaseapp.com',
    storageBucket: 'homework5-c7dbe.firebasestorage.app',
    measurementId: 'G-E0MV4HCV0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHfvrpgaDiPY49iOz-06kPvBiwDzi6gVY',
    appId: '1:730948892593:android:cdc0365ce6639d32f3ef90',
    messagingSenderId: '730948892593',
    projectId: 'homework5-c7dbe',
    storageBucket: 'homework5-c7dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-S4Hq1AZ_ZdtHmUzgeFzlTxp6JQcbZY',
    appId: '1:730948892593:ios:ae5507a1a7d9de18f3ef90',
    messagingSenderId: '730948892593',
    projectId: 'homework5-c7dbe',
    storageBucket: 'homework5-c7dbe.firebasestorage.app',
    iosBundleId: 'com.example.hw5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-S4Hq1AZ_ZdtHmUzgeFzlTxp6JQcbZY',
    appId: '1:730948892593:ios:ae5507a1a7d9de18f3ef90',
    messagingSenderId: '730948892593',
    projectId: 'homework5-c7dbe',
    storageBucket: 'homework5-c7dbe.firebasestorage.app',
    iosBundleId: 'com.example.hw5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDxFiDG6gw2ANaSXPAvKUwqfNCrppKa2M',
    appId: '1:730948892593:web:13db68b540df3a5ef3ef90',
    messagingSenderId: '730948892593',
    projectId: 'homework5-c7dbe',
    authDomain: 'homework5-c7dbe.firebaseapp.com',
    storageBucket: 'homework5-c7dbe.firebasestorage.app',
    measurementId: 'G-VZG8RQYYRM',
  );

}